# Generated by Django 5.0.2 on 2024-03-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default=None, max_length=145),
            preserve_default=False,
        ),
    ]
