# Generated by Django 5.0.2 on 2024-03-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_car_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
    ]
