# Generated by Django 5.0.2 on 2024-03-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_game_typeid_alter_game_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
