# Generated by Django 5.0.2 on 2024-03-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('carMake', models.CharField(max_length=50)),
                ('carModel', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('engineSize', models.FloatField()),
                ('horsePower', models.PositiveIntegerField()),
                ('torque', models.PositiveIntegerField()),
                ('zeroSixty', models.FloatField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
