# Generated by Django 5.0.2 on 2024-03-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='typeId',
        ),
        migrations.AlterField(
            model_name='game',
            name='userId',
            field=models.CharField(max_length=30),
        ),
    ]
