# Generated by Django 5.0.2 on 2024-03-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_car_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
