# Generated by Django 5.0.2 on 2024-03-19 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_rename_userid_game_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='carMake',
            new_name='car_make',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='carModel',
            new_name='car_model',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='engineSize',
            new_name='engine_size',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='horsePower',
            new_name='horse_power',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='zeroSixty',
            new_name='zero_sixty',
        ),
    ]
