# Generated by Django 5.0.2 on 2024-02-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='startingBid',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
