# Generated by Django 5.0.2 on 2024-02-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_startingbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
