# Generated by Django 5.0.2 on 2024-02-25 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_category_alter_listing_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
