# Generated by Django 5.0.2 on 2024-02-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_watchlist_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='userId',
            new_name='user',
        ),
    ]
