# Generated by Django 5.0.2 on 2024-02-25 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_bid_userid_bid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
