# Generated by Django 5.0.2 on 2024-02-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_comment_userid_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
