# Generated by Django 5.0.2 on 2024-02-29 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user_follower',
            new_name='user_followed',
        ),
    ]
